---
# Déploiement de la base de données MySQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql                  # Nom unique du déploiement MySQL
spec:
  selector:
    matchLabels:
      app: mysql              # Sélecteur pour identifier les pods MySQL
  strategy:
    type: Recreate           # Stratégie de mise à jour : recréer le pod plutôt que rolling update
  template:
    metadata:
      labels:
        app: mysql           # Label appliqué aux pods MySQL
    spec:
      containers:
      - name: mysql          # Nom du conteneur
        image: mysql:8.0   # Version spécifique de l'image MySQL
        env:
        - name: MYSQL_ROOT_PASSWORD    # Variable d'environnement pour le mot de passe root
          value: password              # Note: Pour la production, utilisez un Secret
        ports:
        - containerPort: 3306          # Port standard MySQL
          name: mysql
        resources:                     # Limites de ressources recommandées
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:                  # Configuration du montage du volume pour la persistance
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:                         # Définition du volume pour stocker les données MySQL
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc        # Référence à un PVC à créer pour MySQL

---
# Service pour exposer MySQL aux autres pods
apiVersion: v1
kind: Service
metadata:
  name: mysql                  # Nom du service (doit correspondre au MYSQL_HOST dans ConfigMap)
spec:
  ports:
  - port: 3306                # Port exposé par le service
    targetPort: 3306          # Port ciblé dans le conteneur
    name: mysql
  selector:
    app: mysql                # Sélectionne les pods avec le label app: mysql
  clusterIP: None             # Service headless pour une meilleure performance en cluster