# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: getting-started-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: getting-started-app
  template:
    metadata:
      labels:
        app: getting-started-app
    spec:
      containers:
      - name: getting-started-app
        image: getting-started-app:v1
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"